#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
bspc monitor DP-4 -d 9 10 

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
# bspc rule -a firefox desktop='^2'
bspc rule -a "Microsoft Teams - Preview" desktop='^8'
bspc rule -a Steam desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a scpad stick=on state=floating rectangle=900x600+250+250



# Border
bspc config focused_border_color        "#595959"
bspc config normal_border_color         "#aa3f3f3f"
bspc config active_border_color         "#3f3f3f"
bspc config -m locked -n red
bspc config presel_feedback_color "#3f3f3f"

#
# Autostart
xrandr --output DP-0 --mode 1920x1080 --primary --rate 240
xrandr --output DP-4 --mode 1920x1080 --rate 144 --right-of DP-0
xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1
#bspc wm --reorder-monitors DP-0 DP-4
#bspc monitor DVI-I-1 -s DVI-I-2
# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh --docky &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh


